apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-home-lab
  namespace: default
  labels:
    app: test-home-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-home-lab
  template:
    metadata:
      labels:
        app: test-home-lab
    spec:
      containers:
        - name: test-home-lab # Only one container!
          image: ghcr.io/muthuri-dev/test_home_lab:version-16
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
