name: Deploy to Production Cluster

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry using a PAT stored as GHCR_PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 4. Generate Docker image metadata (tags + labels)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=version-${{ github.run_number }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      # 5. Build and push Docker image using the generated tags/labels
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 6. Update the Kubernetes manifest with the new version tag
      - name: Update deployment manifest with new image tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          # If steps.meta.outputs.tags = "ghcr.io/...:version-3 ghcr.io/...:latest",
          # extract just the first tag (split by space).
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | awk '{print $1}')

          sed -i "s|ghcr.io/muthuri-dev/test_home_lab:.*|$FIRST_TAG|g" manifests/deployment.yaml

          git add manifests/deployment.yaml
          git commit -m "Update image to $FIRST_TAG"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
