name: Deploy to Production Cluster

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry using your personal access token (GHCR_PAT)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 4: Build and push the Docker image with a version tag
      - name: Build and push Docker image
        id: build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:version-${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=NestJS application for ${{ github.repository }}

      # Step 5: Echo the image name for verification
      - name: Echo image name
        run: |
          echo "Image: ghcr.io/${{ github.repository }}:version-${{ github.run_number }}"

      # Step 6: Update the deployment manifest with the new image tag and push the change to GitHub
      - name: Update deployment manifest with new image tag
        run: |
          # Configure Git
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          # Update the image tag in manifests/deployment.yaml
          sed -i "s|ghcr.io/${{ github.repository }}:.*|ghcr.io/${{ github.repository }}:version-${{ github.run_number }}|g" manifests/deployment.yaml

          # Commit and push the updated manifest
          git add manifests/deployment.yaml
          git commit -m "Update image to version-${{ github.run_number }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
