name: Deploy to Production Cluster

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with version tag
        id: build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Tag image with a version like version-1, etc.
          tags: ghcr.io/${{ github.repository }}:version-${{ github.run_number }}

      - name: Set up kubectl with prod kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config get-contexts

      - name: Update Kubernetes deployment with new image
        run: |
          # Use the same version tag in the update command
          kubectl set image deployment/test-home-lab test_home_lab=ghcr.io/${{ github.repository }}:version-${{ github.run_number }} -n default
