name: Deploy to Production Cluster

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx for building Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry using your PAT (GHCR_PAT)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 4. Build and push the Docker image with a version tag and latest tag
      - name: Build and push Docker image
        id: build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:version-${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=NestJS application for ${{ github.repository }}

      # 5. Echo the image name for verification
      - name: Echo image name
        run: |
          echo "Image: ghcr.io/${{ github.repository }}:version-${{ github.run_number }}"

      # 6. Update the Kubernetes deployment manifest with the new image tag
      - name: Update deployment manifest with new image tag
        run: |
          # Configure Git so that the bot can commit changes
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          # Update the image tag in manifests/deployment.yaml using sed
          sed -i "s|ghcr.io/${{ github.repository }}:.*|ghcr.io/${{ github.repository }}:version-${{ github.run_number }}|g" manifests/deployment.yaml

          # Commit and push the change back to the repository
          git add manifests/deployment.yaml
          git commit -m "Update image to version-${{ github.run_number }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
